# Generated by Django 4.2 on 2024-10-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scenes', '0001_initial'),
        ('Testproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, help_text='执行时间', verbose_name='执行时间')),
                ('all', models.IntegerField(blank=True, default=0, help_text='总用例数', verbose_name='总用例数')),
                ('success', models.IntegerField(blank=True, default=0, help_text='通过用例数', verbose_name='通过用例数')),
                ('fail', models.IntegerField(blank=True, default=0, help_text='失败用例数', verbose_name='失败用例数')),
                ('error', models.IntegerField(blank=True, default=0, help_text='错误用例数', verbose_name='错误用例数')),
                ('pass_rate', models.CharField(blank=True, default='0', help_text='通过率', max_length=20, verbose_name='通过率')),
                ('tester', models.CharField(blank=True, help_text='执行人', max_length=20, verbose_name='执行人')),
                ('status', models.CharField(default='未执行', help_text='执行状态', max_length=20, verbose_name='执行状态')),
                ('env', models.ForeignKey(help_text='执行环境', max_length=50, on_delete=django.db.models.deletion.PROTECT, to='Testproject.testenv', verbose_name='执行环境')),
            ],
            options={
                'verbose_name': '测试运行记录表',
                'verbose_name_plural': '测试运行记录表',
                'db_table': 'test_record',
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='任务名称', max_length=50, verbose_name='任务名称')),
                ('project', models.ForeignKey(help_text='所属项目id', max_length=50, on_delete=django.db.models.deletion.PROTECT, to='Testproject.testproject', verbose_name='所属项目id')),
                ('scene', models.ManyToManyField(help_text='包含的测试业务流', to='Scenes.testscenes', verbose_name='包含的测试业务流业务流')),
            ],
            options={
                'verbose_name': '测试任务表',
                'verbose_name_plural': '测试任务表',
                'db_table': 'test_task',
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField(blank=True, default=dict, help_text='报告信息', null=True, verbose_name='报告信息')),
                ('record', models.OneToOneField(help_text='运行记录id', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='TestTask.testrecord', verbose_name='运行记录id')),
            ],
            options={
                'verbose_name': '测试报告表',
                'verbose_name_plural': '测试报告表',
                'db_table': 'test_report',
            },
        ),
        migrations.AddField(
            model_name='testrecord',
            name='task',
            field=models.ForeignKey(help_text='所属测试任务id', max_length=50, on_delete=django.db.models.deletion.PROTECT, to='TestTask.testtask', verbose_name='所属测试任务id'),
        ),
    ]
