# Generated by Django 4.2 on 2025-02-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestInterface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinterface',
            name='type',
            field=models.CharField(choices=[('1', '项目接口'), ('2', '第三方接口')], default='1', help_text='接口类型', max_length=10, verbose_name='接口类型'),
        ),
    ]
