# Generated by Django 4.2 on 2025-02-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Performance', '0001_initial'),
    ]

    operations = [
    ]
