# Generated by Django 4.2 on 2024-10-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestInterface', '0001_initial'),
        ('Testproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='业务流名称', max_length=50, verbose_name='业务流名称')),
                ('project', models.ForeignKey(help_text='所属项目id', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Testproject.testproject', verbose_name='所属项目id')),
            ],
            options={
                'verbose_name': '测试业务流',
                'verbose_name_plural': '测试业务流',
                'db_table': 'test_scenes',
            },
        ),
        migrations.CreateModel(
            name='SceneToCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(blank=True, help_text='业务流中的用例执行顺序', null=True, verbose_name='业务流中的用例执行顺序')),
                ('icase', models.ForeignKey(help_text='所属接口用例', max_length=50, on_delete=django.db.models.deletion.PROTECT, to='TestInterface.interfacecase', verbose_name='所属接口用例')),
                ('scene', models.ForeignKey(help_text='所属业务流', max_length=50, on_delete=django.db.models.deletion.PROTECT, to='Scenes.testscenes', verbose_name='所属业务流')),
            ],
            options={
                'verbose_name': '测试业务流中的执行步骤',
                'verbose_name_plural': '测试业务流中的执行步骤',
                'db_table': 'scene_to_case',
            },
        ),
    ]
