# Generated by Django 4.2 on 2024-10-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestTask', '0001_initial'),
        ('Testproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('name', models.CharField(help_text='定时任务名称', max_length=50, verbose_name='定时任务名称')),
                ('status', models.BooleanField(default=False, help_text='定时任务状态', verbose_name='定时任务状态')),
                ('rule', models.CharField(help_text='定时任务规则', max_length=50, verbose_name='定时任务规则')),
                ('env', models.ForeignKey(help_text='执行环境', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Testproject.testenv', verbose_name='执行环境')),
                ('project', models.ForeignKey(help_text='所属项目', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Testproject.testproject', verbose_name='所属项目')),
                ('task', models.ForeignKey(help_text='所属测试任务id', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='TestTask.testtask', verbose_name='所属测试任务id')),
            ],
            options={
                'verbose_name': '定时任务表',
                'verbose_name_plural': '定时任务表',
                'db_table': 'CronJob',
            },
        ),
    ]
