# Generated by Django 4.2 on 2024-10-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestInterface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='bug提交时间', verbose_name='bug提交时间')),
                ('desc', models.CharField(blank=True, help_text='bug描述', max_length=200, verbose_name='bug描述')),
                ('info', models.JSONField(blank=True, default=dict, help_text='测到bug的用例详情', verbose_name='测到bug的用例详情')),
                ('status', models.CharField(help_text='bug状态', max_length=20, verbose_name='bug状态')),
                ('user', models.CharField(blank=True, help_text='提交bug的用户', max_length=20, verbose_name='提交bug的用户')),
                ('interface', models.ForeignKey(help_text='所属接口', on_delete=django.db.models.deletion.CASCADE, to='TestInterface.testinterface', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': 'bug管理表',
                'verbose_name_plural': 'bug管理表',
                'db_table': 'bug_manage',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='BugHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='操作时间', verbose_name='操作时间')),
                ('handle', models.TextField(blank=True, help_text='操作内容', max_length=200, verbose_name='操作内容')),
                ('update_user', models.CharField(blank=True, help_text='操作人', max_length=20, verbose_name='操作人')),
                ('bug', models.ForeignKey(help_text='所属bug', on_delete=django.db.models.deletion.CASCADE, to='BugManage.bugmanage', verbose_name='所属bug')),
            ],
            options={
                'verbose_name': 'bug处理记录表',
                'verbose_name_plural': 'bug处理记录表',
                'db_table': 'bug_handle',
            },
        ),
    ]
